export const loginStyles = {
  loginPaper: {
    width: { xs: "95vw", md: "40vw" },
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    py: { md: "40px", xs: 0 },
    position: "absolute",
    top: { xs: 0, md: "25%" },
    left: { xs: 0, md: "25%" },
  },
  userContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    p: 1,
    m: 1,
    cursor: "pointer",
    width: { xs: 100 },
    alignSelf: "center",
  },
  allusersContainer: {
    display: "flex",
    flexDirection: { md: "row", xs: "column" },
    justifyContent: "space-around",
    width: "100%",
  },
};

export const homeStyles = {
  mainContainer: {
    width: "99.6vw",
    height: "94vh",
    py: "20px",
    position: "relative",
    overflow: "auto",
  },
  disabling: {
    cursor: "not-allowed",
    opacity: "0.2",
  },
  dropDown: {
    display: "flex",
    flexDirection: "row",
    width: "175px",
    justifyContent: "space-around",
    alignItems: "center",
    "&:hover": {
      cursor: "pointer",
      backgroundColor: "#fceed4",
    },
  },
  titleText: {
    display: { xs: "none", md: "flex" },
  },
  active: {
    display: "flex",
    flexDirection: "row",
    width: "175px",
    justifyContent: "space-around",
    alignItems: "center",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "red",
    },
  },
  otherUsers: {
    position: "absolute",
    top: "80x",
    left: "16px",
    flexDirection: "column",
    width: "180px",
  },
  show: {
    display: "flex",
  },
  hide: {
    display: "none",
  },
  navBar: {
    display: "flex",
    width: { md: "95.5%", xs: "100%" },
    justifyContent: "space-between",
    px: { md: 4, xs: 0 },
    alignItems: "center",
  },
  actionsHolder: {
    width: { xs: "98%", md: "50%" },
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    my: 2,
  },
  transactionHolder: {
    width: { xs: "100%", md: "50%" },
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-start",
    my: 2,
  },
  bodyContainer: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
  },
  mainBtnsHolder: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: { xs: "100%" },
  },
  incomeIcon: {
    minWidth: { xs: "150px", md: "225px" },
    height: { xs: "75px", md: "100px" },
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    fontWeight: "bold",
    borderRadius: "10px",
    cursor: "pointer",
  },
  incomeFont: {
    fontSize: { xs: "15px", md: "25px" },
    fontWeight: "bolder",
  },
  green: {
    backgroundColor: "#00A86B",
  },
  red: {
    backgroundColor: "#FD3C4A",
  },
  iconSize: {
    width: { xs: "50px", md: "75px" },
    height: { xs: "50px", md: "75px" },
  },
  listBar: {
    width: { xs: "95%", md: "95%" },
    display: "felx",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    pX: 2,
  },
  listItemsContainer: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "cenetr",
  },
  listItem: {
    width: { xs: "96%", md: "93%" },
    height: 70,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    alignSelf: "center",
  },
  categoryIcon: {
    width: "35px",
    height: "35px",
    display: "flex",
    mr: 1,
    borderRadius: "10px",
    p: 1,
  },
  bell: {
    display: { xs: "none", md: "flex" },
  },
  modalSettings: {
    // backgroundColor: "rgba(0,168,107,1)",
    backgroundColor: "white",
    alignItems: "center",
    p: 5,
  },
  modalTitle: {
    fontSize: "25px",
    color: "green",
    textAlign: "center",
    alignItems: "center",
  },
  modalExpense: {
    fontSize: "25px",
    color: "red",
    textAlign: "center",
    alignItems: "center",
  },
};

export const allTransactions = {
  mainContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100vw",
    height: "100vh",
  },
  innerContainer: {
    width: { md: "70vw", xs: "93vw" },
    height: "90vh",
    overflow: "scroll",
    // border: "solid 2px red",
    p: 2,
  },

  heading: {
    position: "sticky",
    top: "-8px",
    backgroundColor: "white",
    mr: 3,
  },
  footer: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
  },
  header: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    backgroundColor: "white",
    // border: "solid 2px black",
    position: "sticky",
    top: "0px",
    flexWrap: "wrap",
  },
};
